{{- if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
  {{- include "common.annotations" . | nindent 4 }}
  {{- if .Values.configMap.annotations }}
  {{- toYaml .Values.configMap.annotations | nindent 4 }}
  {{- end }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
  {{- if .Values.configMap.labels }}
  {{- toYaml .Values.configMap.labels | nindent 4 }}
  {{- end }}
data:
   {{- range $key, $value := .Values.env }}
   {{ $key }}: {{ $value | quote }}
   {{- end }}
{{- end}}
