{{- if .Values.externalSecret.enabled }}
{{- $appName := include "fullname" . }}
{{- $commonAnnotations := include "common.annotations" . }}
{{- $commonLabels := include "common.labels" . }}
{{- with .Values.externalSecret }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations: {{- $commonAnnotations | nindent 4 }}
  labels: {{- $commonLabels | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval | quote }}
  secretStoreRef:
    name: {{ .secretStore.name }}
    kind: {{ .secretStore.kind }}
  target:
    name: {{ $appName }}-external-secret
    creationPolicy: {{ .creationPolicy }}
    deletionPolicy: {{ .deletionPolicy }}
    template:
      type: {{ .type | default "Opaque" }}
      metadata:
        annotations:
        {{- $commonAnnotations | nindent 10 }}
        {{- if $.Values.externalSecret.annotations }}
        {{- toYaml $.Values.externalSecret.annotations | nindent 10 }}
        {{- end}}
        labels:
        {{- $commonLabels | nindent 10 }}
        {{- if $.Values.externalSecret.labels }}
        {{ toYaml $.Values.externalSecret.labels | nindent 10 }}
        {{- end }}
  {{- if .data}}
  data:
  {{- range $secretKey, $remoteRef := .data}}
  - secretKey: {{ $secretKey }}
    remoteRef:
      - key: {{ $remoteRef.key }}
        {{- if $remoteRef.property }}
        property: {{ $remoteRef.property }}
        {{- end }}
  {{- end }}
  {{- end }}
  {{- if .dataFrom }}
  dataFrom:
    {{- range .dataFrom}}
    - extract:
        key: {{ .key }}
      {{- if .property }}
        property: {{ .property }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end}}
{{- end }}
