{{- if (.Values.secret).enabled }}
{{ $app := include "fullname" . }}
{{ $commonAnnotations := include "common.annotations" . }}
{{ $commonLabels := include "common.labels" .}}
{{- with .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $app }}-static
  namespace: {{ $.Release.Namespace }}
  annotations:
  {{- $commonAnnotations | nindent 4 }}
  {{- if .annotations }}
  {{- toYaml .annotations | nindent 4 }}
  {{- end}}
  labels:
  {{- $commonLabels | nindent 4 }}
  {{- if .labels }}
  {{- toYaml .labels | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
  {{- with .encodedData }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
stringData:
  {{- range $key, $value := .stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
