name: Validate Helm Charts

on:
  pull_request:
    paths:
      - 'charts/**'
  workflow_dispatch:


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.1

      - name: Render Helm Chart
        run: helm template workload ./chart/workload -f values/common.yaml -f values/analyst/prod.values.yaml --skip-schema-validation > rendered.yaml

      - name: Validate rendered manifests with kubeconform
        id: validate
        run: docker run --rm -v "$(pwd):/workspace" ghcr.io/yannh/kubeconform:latest -verbose -summary -output text /workspace/rendered.yaml | tee kubeconform_output.txt

      - name: Process and generate summary
        if: always()
        run: |
          resources=$(cat kubeconform_output.txt | grep '^/workspace/rendered.yaml' | sed -E 's|/workspace/rendered.yaml - ([^[:space:]]+)[[:space:]]+([^[:space:]]+)(.*)|\1 <span style="color:green;">\2</span>\3|')          
          summary=$(cat kubeconform_output.txt | grep '^Summary:' | sed -E 's/(Valid: )([0-9]+)/\1<span style="color:green;">\2<\/span>/; s/(Invalid: )([0-9]+)/\1<span style="color:red;">\2<\/span>/; s/(Errors: )([0-9]+)/\1<span style="color:red;">\2<\/span>/; s/(Skipped: )([0-9]+)/\1<span style="color:white;">\2<\/span>/')
          {
            echo "$resources"
            echo "$summary"
          } >> $GITHUB_STEP_SUMMARY
