name: Validate Helm Charts

on:
  pull_request:
    paths:
      - 'charts/**'
  workflow_dispatch:


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.1

      - name: Render Helm Chart
        run: helm template workload ./chart/workload --skip-schema-validation > rendered.yaml

      - name: Validate rendered manifests with kubeconform
        id: validate
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-summary -output pretty /github/workspace/rendered.yaml > result.txt"

      - name: Generate summary
        run: cat result.txt >> $GITHUB_STEP_SUMMARY
