name: Validate Helm Charts

on:
  pull_request:
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.1

      - name: Render Helm Chart
        run: |
          helm template workload ./chart/workload --skip-schema-validation > rendered.yaml

      - name: Validate rendered manifests with kubeconform
        id: validate
        run: |
          # Run kubeconform and capture the output
          output=$(docker run --rm -v "${{ github.workspace }}:/workspace" ghcr.io/yannh/kubeconform:latest \
            -summary -output text /workspace/rendered.yaml)

          # For debugging you can still echo to console, but don't append to $GITHUB_STEP_SUMMARY
          echo "$output"

          # Store the output so the next step can use it
          echo "output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Process and generate summary
        run: |
          # Get the output from the previous step
          output="${{ steps.validate.outputs.output }}"

          # 1) Process resource lines:
          #    - Only select lines starting with '/workspace/rendered.yaml'
          #    - Remove the file prefix and color the resource name (the second word) in green.
          processed_resources=$(echo "$output" | \
            grep '^/workspace/rendered.yaml' | \
            sed -E 's|/workspace/rendered.yaml - ([^[:space:]]+)[[:space:]]+([^[:space:]]+)(.*)|\1 <span style="color:green;">\2</span>\3|')

          # 2) Add emoji:
          #    - Green check (✅) for lines with "is valid"
          #    - Red cross (❌) for lines with "failed validation"
          processed_resources=$(echo "$processed_resources" | \
            sed -E '/is valid/ s|^|✅ |; /failed validation/ s|^|❌ |')

          # 3) Process the final summary line:
          #    - Color "Valid" in green, "Invalid" and "Errors" in red, and "Skipped" in white.
          processed_summary=$(echo "$output" | \
            grep '^Summary:' | \
            sed -E \
            -e 's/(Valid: )([0-9]+)/\1<span style="color:green;">\2<\/span>/' \
            -e 's/(Invalid: )([0-9]+)/\1<span style="color:red;">\2<\/span>/' \
            -e 's/(Errors: )([0-9]+)/\1<span style="color:red;">\2<\/span>/' \
            -e 's/(Skipped: )([0-9]+)/\1<span style="color:white;">\2<\/span>/')

          # 4) Write only the processed results and summary to the GitHub Step Summary
          {
            echo "$processed_resources"
            echo "$processed_summary"
          } >> $GITHUB_STEP_SUMMARY
